---
kind: cloudscale_ch
enabled: true
dry_run: false
cooldown: 120
min: 0
max: 2

max_step_down: 1

policy:
  target: 5

  # Query an Prometheus endpoint.
  # source: prometheus
  # query: "scalar(avg(haproxy_server_current_sessions))"

  # Query an InfluxDB endpoint.
  # source: influxdb
  # query: "select value from cpu_load_short;"

  # Query a web endpoint.
  # A JSON return o {"metric": <int>} is expected in this case
  source: web
  query:
    url: http://localhost:8000/target.json
    headers: []
    key: "metric"

  # For testing purpose, random metric to get some action
  # source: random
  # config:
  #   start: 1
  #   stop: 10

launch_config:
  flavor: flex-2
  image: debian-10
  zone: lpg1
  tags:
    project: gemini
  ssh_keys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC38qaAv4S1CZmvLD1oOh0a8psSvRmlfqouyjMqlcdcbPWTFmyD3MLOkW/D2qZerka4gCtKT5SmBVLUSx/KzW/YFz70hotC5LBQNbYigiTPjttaZKy7bCQfhrfr3CM52baF6M1OsQ2ZdSAJIp1+G10OP3tmF2BToHulM9P0wHeEo+oFoyerUCL3kgemnTtrjlTGaOUfaAO2Opq2FOxabuabBWB0FNFMCUrtIl465acC1sg5iAEvseOktMQalxYZn5xdCjbD1DE7GN9vz6yyT1SWyGqCFdOODk/H0BlQx+znsu6gyf4aHPTTFtw7k/Ic1zng0wkaQ3Syxuy0o2tEfs3D moser@puzzle.ch
  user_data: |
    #cloud-config
    manage_etc_hosts: true
    package_update: true
    package_upgrade: true
    packages:
      - nginx
