site_name: Scalr - Autoscaling for Clouds
repo_url: https://github.com/ngine-io/scalr
edit_uri: edit/main/docs/
nav:
  - Home: index.md
  - Setup: setup.md
  - Configs:
    - Common: config.md
    - Policy Configs: policy_configs.md
    - Launch Configs: launch_configs.md

theme:
  name: material
  palette:
    primary: cyan
    scheme: slate
markdown_extensions:
  - codehilite
  - admonition
plugins:
  - search
