---
# NOTE: the name is used to prefix and identify resources by a tag.
# If changed, existing resources won't be scaled and must be deleted manually.
---
name: app

enabled: true

dry_run: false

cooldown: 300

min: 0
max: 3
max_step_down: 1
scale_down_selection: oldest


time_rules:
  - name: lights off
    weekdays:
      - Sun
      - Sat
    times_of_day:
      - 23:30-08:00
    days_of_year:
      - Dec24
    configs:
      min: 0
      max: 0
      max_step_down: 10

policies:
  ## Query a web endpoint.
  ## A JSON return o {"metric": <int>} is expected in this case
# - name: my check over web
#   target: 5
#   source: web
#   query: http://localhost:8000/target.json
#   config:
#     headers:
#       Authorization: Bearer xyz
#     key: metric

# - name: influxdb
#   target: 5
#   source: influxdb
#   config:
#     host: localhost
#     port: 8086
#     database: metrics
#     username: root
#     passwort: root
#     measurement: cpu
#     tags: {}

- name: random one to ten
  target: 5
  source: random
  config:
    start: 1
    stop: 10

kind: cloudscale_ch
launch_config:
# Cloudscale.ch
  flavor: flex-2
  image: debian-10
  zone: lpg1
  tags:
    project: gemini
  ssh_keys:
    - ssh-ed25519 AAAAC3N
  user_data: |
    #cloud-config
    manage_etc_hosts: true
    package_update: true
    package_upgrade: true
    packages:
      - nginx

# Hetzner Cloud
  # server_type: cx11
  # image: debian-10
  # labels:
  #   project: gemini
  # location: fsn1
  # ssh_keys:
  #   - resmo
  # user_data: |
  #   #cloud-config
  #   manage_etc_hosts: true
  #   package_update: true
  #   package_upgrade: true
  #   packages:
  #     - nginx

# Cloudstack
  # service_offering: Micro
  # template: Linux Debian 10 (Buster) 64-bit
  # security_groups:
  #   - default
  # zone: de-muc-1
  # ssh_key: rmoser-puzzle
  # tags:
  #   project: gemini
  # root_disk_size: 20
  # user_data: |
  #   #cloud-config
  #   manage_etc_hosts: true
  #   package_update: true
  #   package_upgrade: true
  #   packages:
  #     - nginx

# Digital Ocean
  # size: s-1vcpu-1gb
  # image: debian-10-x64
  # region: ams3
  # ssh_keys:
  #   - 'b5:be:e8:...'
  # tags:
  #   - 'project:gemini'
  # user_data: |
  #   #cloud-config
  #   manage_etc_hosts: true
  #   package_update: true
  #   package_upgrade: true
  #   packages:
  #     - nginx
